import 'package:flutter/material.dart';

import '../theme/app_theme.dart';

enum HabitCategory {
  addiction,
  nutritionQuit,
  digitalDetox,
  mentalQuit,
  healthStart,
  growthStart,
  lifestyleStart,
}

enum HabitKind { quit, start }

class HabitDefinition {
  const HabitDefinition({
    required this.id,
    required this.category,
    required this.kind,
    required this.titleTr,
    required this.titleEn,
    required this.shortTr,
    required this.shortEn,
    required this.icon,
    required this.badgeColor,
    this.hasDetailedSetup = false,
  });

  final String id;
  final HabitCategory category;
  final HabitKind kind;
  final String titleTr;
  final String titleEn;
  final String shortTr;
  final String shortEn;
  final IconData icon;
  final Color badgeColor;
  final bool hasDetailedSetup;
}

class HabitCatalog {
  static const Color _coral = Color(0xFFE59A94);
  static const Color _sand = Color(0xFFEBCB93);
  static const Color _sage = Color(0xFF98B48D);
  static const Color _lilac = Color(0xFFC4B5D4);
  static const Color _rose = Color(0xFFD4A5A5);
  static const Color _mint = Color(0xFF7FA88A);
  static const Color _sky = Color(0xFF8FA8B8);
  static const Color _peach = Color(0xFFE8B89A);

  static const List<HabitDefinition> all = [
    // --- Bağımlılık ---
    HabitDefinition(
      id: 'smoking',
      category: HabitCategory.addiction,
      kind: HabitKind.quit,
      titleTr: 'Sigara bırakma',
      titleEn: 'Quit smoking',
      shortTr: 'Sigara',
      shortEn: 'Smoking',
      icon: Icons.smoking_rooms_outlined,
      badgeColor: _coral,
      hasDetailedSetup: true,
    ),
    HabitDefinition(
      id: 'alcohol',
      category: HabitCategory.addiction,
      kind: HabitKind.quit,
      titleTr: 'Alkol bırakma',
      titleEn: 'Quit alcohol',
      shortTr: 'Alkol',
      shortEn: 'Alcohol',
      icon: Icons.wine_bar_outlined,
      badgeColor: _sand,
      hasDetailedSetup: true,
    ),
    HabitDefinition(
      id: 'drugs',
      category: HabitCategory.addiction,
      kind: HabitKind.quit,
      titleTr: 'Uyuşturucu bırakma',
      titleEn: 'Quit drugs',
      shortTr: 'Uyuşturucu',
      shortEn: 'Drugs',
      icon: Icons.medication_outlined,
      badgeColor: _rose,
      hasDetailedSetup: true,
    ),
    HabitDefinition(
      id: 'masturbation',
      category: HabitCategory.addiction,
      kind: HabitKind.quit,
      titleTr: 'Mastürbasyon bırakma',
      titleEn: 'Quit masturbation',
      shortTr: 'Mastürbasyon',
      shortEn: 'Masturbation',
      icon: Icons.self_improvement_outlined,
      badgeColor: _lilac,
    ),

    // --- 1. Beslenme & Sağlık (bırakma) ---
    HabitDefinition(
      id: 'quit_soda',
      category: HabitCategory.nutritionQuit,
      kind: HabitKind.quit,
      titleTr: 'Gazlı içecek bırakma',
      titleEn: 'Quit soda / soft drinks',
      shortTr: 'Gazlı içecek',
      shortEn: 'Soda',
      icon: Icons.local_cafe_outlined,
      badgeColor: _coral,
    ),
    HabitDefinition(
      id: 'quit_sugar_junk',
      category: HabitCategory.nutritionQuit,
      kind: HabitKind.quit,
      titleTr: 'Şeker & abur cubur bırakma',
      titleEn: 'Quit sugar & junk food',
      shortTr: 'Şeker',
      shortEn: 'Sugar',
      icon: Icons.cookie_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'quit_packaged_food',
      category: HabitCategory.nutritionQuit,
      kind: HabitKind.quit,
      titleTr: 'Paketli gıda bırakma',
      titleEn: 'Quit packaged food',
      shortTr: 'Paketli gıda',
      shortEn: 'Packaged food',
      icon: Icons.inventory_2_outlined,
      badgeColor: _peach,
    ),
    HabitDefinition(
      id: 'quit_fast_food',
      category: HabitCategory.nutritionQuit,
      kind: HabitKind.quit,
      titleTr: 'Fast food bırakma',
      titleEn: 'Quit fast food',
      shortTr: 'Fast food',
      shortEn: 'Fast food',
      icon: Icons.fastfood_outlined,
      badgeColor: _coral,
    ),
    HabitDefinition(
      id: 'quit_late_night_eating',
      category: HabitCategory.nutritionQuit,
      kind: HabitKind.quit,
      titleTr: 'Gece yeme alışkanlığını bırakma',
      titleEn: 'Stop late-night eating',
      shortTr: 'Gece yeme',
      shortEn: 'Night eating',
      icon: Icons.nightlight_outlined,
      badgeColor: _lilac,
    ),
    HabitDefinition(
      id: 'quit_excess_caffeine',
      category: HabitCategory.nutritionQuit,
      kind: HabitKind.quit,
      titleTr: 'Aşırı kahve / kafein bırakma',
      titleEn: 'Cut excess caffeine',
      shortTr: 'Kafein',
      shortEn: 'Caffeine',
      icon: Icons.coffee_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'reduce_salt',
      category: HabitCategory.nutritionQuit,
      kind: HabitKind.quit,
      titleTr: 'Tuz kullanımını azaltma',
      titleEn: 'Reduce salt intake',
      shortTr: 'Tuz',
      shortEn: 'Salt',
      icon: Icons.spa_outlined,
      badgeColor: _sky,
    ),
    HabitDefinition(
      id: 'quit_processed_meat',
      category: HabitCategory.nutritionQuit,
      kind: HabitKind.quit,
      titleTr: 'Eti / işlenmiş eti bırakma',
      titleEn: 'Quit meat / processed meat',
      shortTr: 'İşlenmiş et',
      shortEn: 'Processed meat',
      icon: Icons.set_meal_outlined,
      badgeColor: _rose,
    ),

    // --- 2. Teknoloji & Dijital Detoks ---
    HabitDefinition(
      id: 'social_media_detox',
      category: HabitCategory.digitalDetox,
      kind: HabitKind.quit,
      titleTr: 'Sosyal medya detoksu',
      titleEn: 'Social media detox',
      shortTr: 'Sosyal medya',
      shortEn: 'Social media',
      icon: Icons.public_off_outlined,
      badgeColor: _sky,
    ),
    HabitDefinition(
      id: 'quit_instagram_tiktok',
      category: HabitCategory.digitalDetox,
      kind: HabitKind.quit,
      titleTr: 'Instagram / TikTok bırakma',
      titleEn: 'Quit Instagram / TikTok',
      shortTr: 'IG / TikTok',
      shortEn: 'IG / TikTok',
      icon: Icons.video_library_outlined,
      badgeColor: _coral,
    ),
    HabitDefinition(
      id: 'limit_screen_time',
      category: HabitCategory.digitalDetox,
      kind: HabitKind.quit,
      titleTr: 'Ekran süresini sınırlama',
      titleEn: 'Limit screen time',
      shortTr: 'Ekran süresi',
      shortEn: 'Screen time',
      icon: Icons.timelapse_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'quit_mobile_games',
      category: HabitCategory.digitalDetox,
      kind: HabitKind.quit,
      titleTr: 'Mobil oyun bırakma',
      titleEn: 'Quit mobile games',
      shortTr: 'Mobil oyun',
      shortEn: 'Mobile games',
      icon: Icons.sports_esports_outlined,
      badgeColor: _lilac,
    ),
    HabitDefinition(
      id: 'quit_pc_console_games',
      category: HabitCategory.digitalDetox,
      kind: HabitKind.quit,
      titleTr: 'PC / konsol oyunlarını bırakma',
      titleEn: 'Quit PC / console games',
      shortTr: 'PC / konsol',
      shortEn: 'PC / console',
      icon: Icons.gamepad_outlined,
      badgeColor: _peach,
    ),
    HabitDefinition(
      id: 'no_phone_in_bed',
      category: HabitCategory.digitalDetox,
      kind: HabitKind.quit,
      titleTr: 'Yataktan önce telefona bakmama',
      titleEn: 'No phone before bed',
      shortTr: 'Yatak öncesi telefon',
      shortEn: 'Phone before bed',
      icon: Icons.bedtime_outlined,
      badgeColor: _lilac,
    ),
    HabitDefinition(
      id: 'no_phone_on_wake',
      category: HabitCategory.digitalDetox,
      kind: HabitKind.quit,
      titleTr: 'Sabah uyanır uyanmaz telefona bakmama',
      titleEn: 'No phone right after waking',
      shortTr: 'Sabah telefon',
      shortEn: 'Morning phone',
      icon: Icons.wb_sunny_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'no_late_screens',
      category: HabitCategory.digitalDetox,
      kind: HabitKind.quit,
      titleTr: 'Gece geç saatte ekran karşısında kalmama',
      titleEn: 'No late-night screens',
      shortTr: 'Gece ekran',
      shortEn: 'Late screens',
      icon: Icons.desktop_access_disabled_outlined,
      badgeColor: _sky,
    ),

    // --- 3. Zihinsel & Psikolojik ---
    HabitDefinition(
      id: 'quit_complaining',
      category: HabitCategory.mentalQuit,
      kind: HabitKind.quit,
      titleTr: 'Şikayet etmeyi / mızmızlanmayı bırakma',
      titleEn: 'Stop complaining',
      shortTr: 'Şikayet',
      shortEn: 'Complaining',
      icon: Icons.mood_bad_outlined,
      badgeColor: _rose,
    ),
    HabitDefinition(
      id: 'quit_gossip',
      category: HabitCategory.mentalQuit,
      kind: HabitKind.quit,
      titleTr: 'Dedikodu yapmayı bırakma',
      titleEn: 'Stop gossiping',
      shortTr: 'Dedikodu',
      shortEn: 'Gossip',
      icon: Icons.forum_outlined,
      badgeColor: _peach,
    ),
    HabitDefinition(
      id: 'quit_procrastination',
      category: HabitCategory.mentalQuit,
      kind: HabitKind.quit,
      titleTr: 'Erteleme alışkanlığını bırakma',
      titleEn: 'Stop procrastinating',
      shortTr: 'Erteleme',
      shortEn: 'Procrastination',
      icon: Icons.hourglass_empty_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'quit_swearing',
      category: HabitCategory.mentalQuit,
      kind: HabitKind.quit,
      titleTr: 'Küfür / argo kullanımını bırakma',
      titleEn: 'Stop swearing',
      shortTr: 'Küfür',
      shortEn: 'Swearing',
      icon: Icons.record_voice_over_outlined,
      badgeColor: _coral,
    ),
    HabitDefinition(
      id: 'quit_nail_biting',
      category: HabitCategory.mentalQuit,
      kind: HabitKind.quit,
      titleTr: 'Tırnak yemeyi bırakma',
      titleEn: 'Stop nail biting',
      shortTr: 'Tırnak yeme',
      shortEn: 'Nail biting',
      icon: Icons.back_hand_outlined,
      badgeColor: _lilac,
    ),
    HabitDefinition(
      id: 'quit_impulse_spending',
      category: HabitCategory.mentalQuit,
      kind: HabitKind.quit,
      titleTr: 'Aşırı harcama / fuzuli alışverişi bırakma',
      titleEn: 'Stop impulse spending',
      shortTr: 'Fuzuli alışveriş',
      shortEn: 'Impulse buying',
      icon: Icons.shopping_bag_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'quit_late_sleep',
      category: HabitCategory.mentalQuit,
      kind: HabitKind.quit,
      titleTr: 'Geç yatmayı bırakma (erken uyumak)',
      titleEn: 'Stop going to bed late',
      shortTr: 'Geç yatma',
      shortEn: 'Late bedtime',
      icon: Icons.hotel_outlined,
      badgeColor: _sky,
    ),
    HabitDefinition(
      id: 'quit_lying',
      category: HabitCategory.mentalQuit,
      kind: HabitKind.quit,
      titleTr: 'Aşırı yalan / beyaz yalan söylemeyi bırakma',
      titleEn: 'Stop lying / white lies',
      shortTr: 'Yalan',
      shortEn: 'Lying',
      icon: Icons.psychology_outlined,
      badgeColor: _rose,
    ),

    // --- 4. Sağlık & Spor (başlama) ---
    HabitDefinition(
      id: 'sports',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Spora / egzersize başlama',
      titleEn: 'Start exercise / sports',
      shortTr: 'Spor',
      shortEn: 'Sports',
      icon: Icons.directions_run_outlined,
      badgeColor: _mint,
      hasDetailedSetup: true,
    ),
    HabitDefinition(
      id: 'daily_walk',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Düzenli yürüyüş yapma',
      titleEn: 'Daily walking',
      shortTr: 'Yürüyüş',
      shortEn: 'Walking',
      icon: Icons.directions_walk_outlined,
      badgeColor: _sage,
    ),
    HabitDefinition(
      id: 'drink_water',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Yeterli su içme',
      titleEn: 'Drink enough water',
      shortTr: 'Su içme',
      shortEn: 'Water',
      icon: Icons.water_drop_outlined,
      badgeColor: _sky,
    ),
    HabitDefinition(
      id: 'cold_shower',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Soğuk duş alma',
      titleEn: 'Cold showers',
      shortTr: 'Soğuk duş',
      shortEn: 'Cold shower',
      icon: Icons.shower_outlined,
      badgeColor: _sky,
    ),
    HabitDefinition(
      id: 'skincare',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Yüz serumu / cilt bakımı',
      titleEn: 'Skincare routine',
      shortTr: 'Cilt bakımı',
      shortEn: 'Skincare',
      icon: Icons.face_retouching_natural_outlined,
      badgeColor: _peach,
    ),
    HabitDefinition(
      id: 'posture',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Postür / duruş düzeltme',
      titleEn: 'Posture exercises',
      shortTr: 'Postür',
      shortEn: 'Posture',
      icon: Icons.accessibility_new_outlined,
      badgeColor: _mint,
    ),
    HabitDefinition(
      id: 'early_rise',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Erken uyanma',
      titleEn: 'Wake up early',
      shortTr: 'Erken uyanma',
      shortEn: 'Early rise',
      icon: Icons.alarm_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'floss',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Diş ipi kullanma',
      titleEn: 'Floss daily',
      shortTr: 'Diş ipi',
      shortEn: 'Flossing',
      icon: Icons.health_and_safety_outlined,
      badgeColor: _sage,
    ),
    HabitDefinition(
      id: 'diet',
      category: HabitCategory.healthStart,
      kind: HabitKind.start,
      titleTr: 'Diyet / beslenme düzeni',
      titleEn: 'Diet / nutrition plan',
      shortTr: 'Diyet',
      shortEn: 'Diet',
      icon: Icons.eco_outlined,
      badgeColor: _sage,
      hasDetailedSetup: true,
    ),

    // --- 5. Kişisel Gelişim ---
    HabitDefinition(
      id: 'read_books',
      category: HabitCategory.growthStart,
      kind: HabitKind.start,
      titleTr: 'Kitap okuma',
      titleEn: 'Read books',
      shortTr: 'Kitap',
      shortEn: 'Reading',
      icon: Icons.menu_book_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'meditation',
      category: HabitCategory.growthStart,
      kind: HabitKind.start,
      titleTr: 'Meditasyon / nefes egzersizi',
      titleEn: 'Meditation / breathing',
      shortTr: 'Meditasyon',
      shortEn: 'Meditation',
      icon: Icons.self_improvement,
      badgeColor: _lilac,
    ),
    HabitDefinition(
      id: 'journaling',
      category: HabitCategory.growthStart,
      kind: HabitKind.start,
      titleTr: 'Günlük / journal tutma',
      titleEn: 'Keep a journal',
      shortTr: 'Günlük',
      shortEn: 'Journal',
      icon: Icons.edit_note_outlined,
      badgeColor: _peach,
    ),
    HabitDefinition(
      id: 'learn_language',
      category: HabitCategory.growthStart,
      kind: HabitKind.start,
      titleTr: 'Yeni bir dil çalışma',
      titleEn: 'Learn a language',
      shortTr: 'Dil',
      shortEn: 'Language',
      icon: Icons.translate_outlined,
      badgeColor: _sky,
    ),
    HabitDefinition(
      id: 'instrument_practice',
      category: HabitCategory.growthStart,
      kind: HabitKind.start,
      titleTr: 'Enstrüman pratiği',
      titleEn: 'Practice an instrument',
      shortTr: 'Enstrüman',
      shortEn: 'Instrument',
      icon: Icons.music_note_outlined,
      badgeColor: _coral,
    ),
    HabitDefinition(
      id: 'podcasts',
      category: HabitCategory.growthStart,
      kind: HabitKind.start,
      titleTr: 'Podcast / sesli kitap dinleme',
      titleEn: 'Listen to podcasts / audiobooks',
      shortTr: 'Podcast',
      shortEn: 'Podcasts',
      icon: Icons.headphones_outlined,
      badgeColor: _mint,
    ),
    HabitDefinition(
      id: 'learn_coding',
      category: HabitCategory.growthStart,
      kind: HabitKind.start,
      titleTr: 'Kodlama / yazılım çalışma',
      titleEn: 'Practice coding',
      shortTr: 'Kodlama',
      shortEn: 'Coding',
      icon: Icons.code_outlined,
      badgeColor: _sky,
    ),
    HabitDefinition(
      id: 'gratitude_journal',
      category: HabitCategory.growthStart,
      kind: HabitKind.start,
      titleTr: 'Şükür günlüğü tutma',
      titleEn: 'Gratitude journal',
      shortTr: 'Şükür günlüğü',
      shortEn: 'Gratitude',
      icon: Icons.favorite_outline,
      badgeColor: _rose,
    ),

    // --- 6. Yaşam Tarzı & Düzen ---
    HabitDefinition(
      id: 'make_bed',
      category: HabitCategory.lifestyleStart,
      kind: HabitKind.start,
      titleTr: 'Yatağı toplama',
      titleEn: 'Make the bed',
      shortTr: 'Yatak toplama',
      shortEn: 'Make bed',
      icon: Icons.bed_outlined,
      badgeColor: _sage,
    ),
    HabitDefinition(
      id: 'tidy_space',
      category: HabitCategory.lifestyleStart,
      kind: HabitKind.start,
      titleTr: 'Evi / çalışma masasını toplu tutma',
      titleEn: 'Keep space tidy',
      shortTr: 'Düzen',
      shortEn: 'Tidiness',
      icon: Icons.cleaning_services_outlined,
      badgeColor: _mint,
    ),
    HabitDefinition(
      id: 'budget_tracking',
      category: HabitCategory.lifestyleStart,
      kind: HabitKind.start,
      titleTr: 'Bütçe / harcama takibi',
      titleEn: 'Track budget / spending',
      shortTr: 'Bütçe',
      shortEn: 'Budget',
      icon: Icons.account_balance_wallet_outlined,
      badgeColor: _sand,
    ),
    HabitDefinition(
      id: 'call_family',
      category: HabitCategory.lifestyleStart,
      kind: HabitKind.start,
      titleTr: 'Aileyi / arkadaşları düzenli arama',
      titleEn: 'Call family / friends regularly',
      shortTr: 'Arama',
      shortEn: 'Calls',
      icon: Icons.call_outlined,
      badgeColor: _peach,
    ),
    HabitDefinition(
      id: 'zero_waste',
      category: HabitCategory.lifestyleStart,
      kind: HabitKind.start,
      titleTr: 'Sıfır atık / dönüşüm odaklı yaşama',
      titleEn: 'Zero-waste lifestyle',
      shortTr: 'Sıfır atık',
      shortEn: 'Zero waste',
      icon: Icons.recycling_outlined,
      badgeColor: _sage,
    ),
    HabitDefinition(
      id: 'plant_care',
      category: HabitCategory.lifestyleStart,
      kind: HabitKind.start,
      titleTr: 'Bitki sulama / bakım',
      titleEn: 'Plant care',
      shortTr: 'Bitki bakımı',
      shortEn: 'Plants',
      icon: Icons.local_florist_outlined,
      badgeColor: _mint,
    ),
    HabitDefinition(
      id: 'plan_tomorrow',
      category: HabitCategory.lifestyleStart,
      kind: HabitKind.start,
      titleTr: 'Günün planını bir gün önce hazırlama',
      titleEn: 'Plan tomorrow tonight',
      shortTr: 'Gün planı',
      shortEn: 'Day plan',
      icon: Icons.event_note_outlined,
      badgeColor: _sky,
    ),
    HabitDefinition(
      id: 'home_cooked_only',
      category: HabitCategory.lifestyleStart,
      kind: HabitKind.start,
      titleTr: 'Sadece ev yemeği yeme',
      titleEn: 'Eat only home-cooked meals',
      shortTr: 'Ev yemeği',
      shortEn: 'Home cooking',
      icon: Icons.soup_kitchen_outlined,
      badgeColor: _coral,
    ),
  ];

  static final Map<String, HabitDefinition> _byId = {
    for (final d in all) d.id: d,
  };

  static HabitDefinition? byId(String id) => _byId[id];

  static HabitDefinition require(String id) =>
      _byId[id] ??
      HabitDefinition(
        id: id,
        category: HabitCategory.lifestyleStart,
        kind: HabitKind.start,
        titleTr: id,
        titleEn: id,
        shortTr: id,
        shortEn: id,
        icon: Icons.flag_outlined,
        badgeColor: AppTheme.sage,
      );

  static List<HabitDefinition> byCategory(HabitCategory category) =>
      all.where((d) => d.category == category).toList(growable: false);

  static const List<HabitCategory> orderedCategories = HabitCategory.values;
}